// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type JobStatus struct {
	Label string `json:"label"`
	Value int    `json:"value"`
}

type JobsByAvgIncome struct {
	Value float64 `json:"value"`
	Label string  `json:"label"`
}
